version: '3.5'
networks:
  docker_nw:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.201.0/24

services:
  splunk_enterprise:
    build:
        context: .
        dockerfile: splunkenterprise/Dockerfile
    tty: true
    container_name: 'spe2'
    cap_add:
      - SYS_ADMIN
    ports:
      - "18000:8000"
      - "13389:3389"
    networks:
      docker_nw:
        ipv4_address: 192.168.201.11
    command: /sbin/init
